config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
        registrations: "users/registrations",
        omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :reports do
    resources :comments, only: [:create, :edit, :update, :destroy], module: :reports
  end
  resources :books do
    resources :comments, only: [:create, :edit, :update, :destroy], module: :books
  end
  resources :users do
    resources :followings, only: :index, controller: "users/followings"
    resources :followers, only: :index, controller: "users/followers"
  end
  resources :users, only: [:index, :show]
  resources :follows, only: [:create, :destroy]
  root to: "books#index"
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  mount_uploader :picture, PictureUploader
  has_many :comments, as: :commentable
  belongs_to :user
end

app/controllers/books/comments_controller.rb
# frozen_string_literal: true

class Books::CommentsController < CommentsController
  before_action :set_commentable

  private
    def set_commentable
      @commentable = Book.find(params[:book_id])
    end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  def index
    @books = Book.where(user_id: current_user.following).or(Book.where(user_id: current_user)).page(params[:page])
  end

  # GET /books/1
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
    current_user.books.find(params[:id])
  end

  # POST /books
  def create
    @book = current_user.books.new(book_params)
    if @book.save
      redirect_to @book, notice: t("flash.create")
    else
      render :new
    end
  end

  # PATCH/PUT /books/1
  def update
    if @book = current_user.books.find(params[:id])
      @book.update(book_params)
      redirect_to @book, notice: t("flash.update")
    else
      render :edit
    end
  end

  # DELETE /books/1
  def destroy
    @book = current_user.books.find(params[:id])
    @book.destroy
    redirect_to books_url, notice: t("flash.destroy")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :memo, :author, :picture)
    end
end

app/views/books/_form.html.slim
= form_with(model: book, local: true) do |form|
  - if book.errors.any?
    #error_explanation
      h2
        = pluralize(book.errors.count, "error")
        |  prohibited this book from being saved:
      ul
        - book.errors.full_messages.each do |message|
          li
            = message
  .field
    = form.label :title
    = form.text_field :title
  .field
    = form.label :memo
    = form.text_area :memo
  .field
    = form.label :picture
    = form.file_field :picture
  .actions
    = form.submit

app/views/books/edit.html.slim
h1
  = t("Editing Book")
= render "form", book: @book
= link_to t("link.show"), @book
|  | 
= link_to t("link.back"), books_path

app/views/books/index.html.slim
h1
  = t("Books")
table
  thead
    tr
      th = Book.human_attribute_name(:user_name)
      th = Book.human_attribute_name(:title)
      th = Book.human_attribute_name(:memo)
      th = Book.human_attribute_name(:picture)
      th[colspan="3"]
  tbody
    - @books.each do |book|
      tr
        td = link_to book.user.name, user_path(id: book.user_id)
        td = book.title
        td = book.memo
        td = book.picture
        td = link_to t("link.show"), book
        - if book.user_id == current_user.id
          td = link_to t("link.edit"), edit_book_path(book)
          td = link_to t("link.destroy"), book, method: :delete, data: { confirm: t("alert.sure") }
= paginate @books
br
= link_to t("link.new"), new_book_path

app/views/books/new.html.slim
h1
  = t("New Book")
= render "form", book: @book
= link_to t("link.back"), books_path

app/views/books/show.html.slim
p
  strong
    = Book.human_attribute_name(:title)
    | :
  = @book.title
p
  strong
    = Book.human_attribute_name(:memo)
    | :
  = @book.memo
p
  strong
    = Book.human_attribute_name(:picture)
    | :
  = image_tag(@book.picture_url) if @book.picture.present?
- if @book.user_id == current_user.id
  = link_to t("link.Edit"), edit_book_path(@book)
  |  | 
  = link_to t("link.Destroy"), @book, method: :delete, data: { confirm: t("alert.sure") }
  |  | 
= render "comments/comments", commentable: @book
h3
  = t("New Comment")
= render "comments/form", commentable: @book, comment: @book.comments.new
= link_to t("link.Back"), books_path