config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
        registrations: "users/registrations",
        omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :reports do
    resources :comments, only: [:create, :edit, :update, :destroy], module: :reports
  end
  resources :books do
    resources :comments, only: [:create, :edit, :update, :destroy], module: :books
  end
  resources :users do
    resources :followings, only: :index, controller: "users/followings"
    resources :followers, only: :index, controller: "users/followers"
  end
  resources :users, only: [:index, :show]
  resources :follows, only: [:create, :destroy]
  root to: "books#index"
end

app/models/report.rb
# frozen_string_literal: true

class Report < ApplicationRecord
  has_many :comments, as: :commentable
  belongs_to :user
end

app/controllers/reports/comments_controller.rb
# frozen_string_literal: true

class Reports::CommentsController < CommentsController
  before_action :set_commentable

  private
    def set_commentable
      @commentable = Report.find(params[:report_id])
    end
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  def index
    @reports = Report.where(user_id: current_user.following).or(Report.where(user_id: current_user)).page(params[:page])
  end

  def show
  end

  def new
    @report = Report.new
  end

  def edit
    current_user.reports.find(params[:id])
  end

  def create
    @report = current_user.reports.new(report_params)
    if @report.save
      redirect_to @report, notice: t("reports.created.notice")
    else
      render :new
    end
  end

  def update
    if @report = current_user.reports.find(params[:id])
      @report.update(report_params)
      redirect_to @report, notice: t("reports.updated.notice")
    else
      render :edit
    end
  end

  def destroy
    @report = current_user.reports.find(params[:id])
    @report.destroy
    redirect_to reports_url, notice: t("reports.destroy.notice")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def report_params
      params.require(:report).permit(:title, :content, :user_id)
    end
end

app/views/reports/_form.html.slim
= form_with(model: report, local: true) do |form|
  - if report.errors.any?
    #error_explanation
      h2
        = pluralize(report.errors.count, "error")
        |  prohibited this report from being saved:
      ul
        - report.errors.full_messages.each do |message|
          li
            = message
  .field
    = form.label :title
    = form.text_field :title
  .field
    = form.label :content
    = form.text_area :content
  .actions
    = form.submit

app/views/reports/edit.html.slim
h1
  = t("reports.update.title")
= render 'form', report: @report
= link_to t("link.show"), @report
|  | 
= link_to t("link.back"), reports_path

app/views/reports/index.html.slim
h1
  = t("reports.index.title")
table
  thead
    tr
      th
        = User.human_attribute_name(:user_name)
      th
        = Report.human_attribute_name(:title)
      th
        = Report.human_attribute_name(:content)
      th[colspan="3"]
  tbody
    - @reports.each do |report|
      tr
        td
          = link_to report.user.name, user_path(report.user_id)
        td
          = report.title
        td
          = report.content
        td
          = link_to t("link.show"), report
        - if report.user_id == current_user.id
          td
            = link_to t("link.edit"), edit_report_path(report)
          td
            = link_to t("link.destroy"), report, method: :delete, data: { confirm: t("alert.sure") }
br
= link_to t("link.new"), new_report_path
|  | 
= link_to t("link.top"), root_path

app/views/reports/new.html.slim
h1
  = t("reports.create.title")
= render 'form', report: @report
= link_to t("link.back"), reports_path
|  | 
= link_to t("link.top"), root_path

app/views/reports/show.html.slim
p
  strong
    = Report.human_attribute_name(:title)
    | :
  = @report.title
p
  strong
    = Report.human_attribute_name(:content)
    | :
  = @report.content
- if @user_id == current_user.id
  = link_to t("link.edit"), edit_report_path(@report)
  |  | 
  = link_to t("link.destroy"), @repot, method: :delete, data: { confirm: t("alert.sure") }
  |  | 
= render "comments/comments", commentable: @report
h3
  = t("New Comment")
= render "comments/form", commentable: @report, comment: @report.comments.new
= link_to t("link.back"), reports_path
|  | 
= link_to t("link.top"), root_path