config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
        registrations: "users/registrations",
        omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :reports do
    resources :comments, only: [:create, :edit, :update, :destroy], module: :reports
  end
  resources :books do
    resources :comments, only: [:create, :edit, :update, :destroy], module: :books
  end
  resources :users do
    resources :followings, only: :index, controller: "users/followings"
    resources :followers, only: :index, controller: "users/followers"
  end
  resources :users, only: [:index, :show]
  resources :follows, only: [:create, :destroy]
  root to: "books#index"
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | BooksApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_pack_tag "application", "data-turbolinks-track": "reload"

  body
    p.navbar-text.pull-right
      - if user_signed_in?
        strong
          = current_user.name
        = t("Logged in as")
        = link_to t("Profile"), user_path(id: current_user.id), class: "navbar-link"
        |  |
        = link_to t("All users"), users_path
        |  |
        = link_to t("reports.index.title"), reports_path
        |  |
        = link_to t("Logout"), destroy_user_session_path, method: :delete, class: "navbar-link"
      - else
        = link_to t("Sign up"), new_user_registration_path, class: "navbar-link"
        |  |
        = link_to t("Login"), new_user_session_path, class: "navbar-link"
    - if notice
      p.alert.alert-success
        = notice
    - if alert
      p.alert.alert-danger
        = alert
    = yield